<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXdBeGJG\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXdBeGJG/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXdBeGJG.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXdBeGJG\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXdBeGJG\App_KernelDevDebugContainer([
    'container.build_hash' => 'XdBeGJG',
    'container.build_id' => 'b1f02d70',
    'container.build_time' => 1708960116,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXdBeGJG');
